
[chat_utilities]
	vanquisher_chat = 4

	[chat_utilities.stats]
		vanquisher_chat = 3

	[chat_utilities.vanquishers]
		vanquisher_chat = 0

[stats]

	[stats.stats]
		tick_speed_block = 3
		vanquisher_chat = 3

